Repository Arkingco/42_cub3d, pull requests merged in 2022-11, with the labels that each got.

#28 Feat/parse map
  includes/parse_map.h
  srcs/parse_map/Makefile
  srcs/parse_map/asset/.cubaa
  srcs/parse_map/asset/a.cub.cub
  srcs/parse_map/asset/example.cub
  srcs/parse_map/asset/map_in_pdf.cub
  srcs/parse_map/cub3D
  srcs/parse_map/get_map.c
  srcs/parse_map/init_element.c
  srcs/parse_map/init_map_content.c
  srcs/parse_map/init_map_info.c
  srcs/parse_map/is_valid_map.c
  srcs/parse_map/main.c
  srcs/parse_map/pass_element.c
  srcs/parse_map/pass_empty_line.c
  srcs/parse_map/process_color.c
  srcs/parse_map/process_texture_path.c
Labels: enhancement

#33 Refactor/코드 norm 맞추기
  Makefile
  cub3D
  includes/cub3d.h
  includes/error.h
  includes/game_view.h
  includes/key.h
  includes/minimap.h
  includes/so_long.h
  includes/struct.h
  minilibx_opengl_20191021/libmlx.a
  srcs/error/error.c
  srcs/event/key.c
  srcs/event/move.c
  srcs/game_view/game_dda.c
  srcs/game_view/game_draw.c
  srcs/game_view/game_view.c
  srcs/main.c
  srcs/mini_map/draw_mini_map.c
  srcs/mini_map/draw_mini_player.c
  srcs/mini_map/draw_mini_ray.c
  srcs/parser/error_utils.c
  srcs/parser/parse_error.c
  srcs/set_game/set_mlx.c
  srcs/set_game/set_texture.c
  test
Labels: refactoring

#35 벽 판정 길이 줄이기 밑 mlx함수 랩핑
  includes/error.h
  includes/game_view.h
  includes/key.h
  srcs/event/key.c
  srcs/main.c
  srcs/set_game/set_game.c
  srcs/set_game/set_mlx.c
Labels: bug, refactoring
